var DADOS = {
    "classificacao":  [
                          {
                              "nome":  "João",
                              "pontos":  53,
                              "jogos":  23,
                              "historico":  [
                                                3,
                                                3,
                                                1,
                                                3,
                                                3,
                                                3,
                                                0,
                                                1,
                                                3,
                                                3,
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                3,
                                                3,
                                                0,
                                                3,
                                                3,
                                                3,
                                                "F"
                                            ],
                              "gols":  44
                          },
                          {
                              "nome":  "Jorge",
                              "pontos":  37,
                              "jogos":  24,
                              "historico":  [
                                                "F",
                                                3,
                                                1,
                                                0,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                3,
                                                3,
                                                3,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                0,
                                                3,
                                                3,
                                                0,
                                                3,
                                                3,
                                                0
                                            ],
                              "gols":  40
                          },
                          {
                              "nome":  "Tampico",
                              "pontos":  37,
                              "jogos":  23,
                              "historico":  [
                                                "F",
                                                3,
                                                1,
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3,
                                                3,
                                                3,
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                3,
                                                0,
                                                0,
                                                3
                                            ],
                              "gols":  35
                          },
                          {
                              "nome":  "Bruno",
                              "pontos":  32,
                              "jogos":  27,
                              "historico":  [
                                                3,
                                                0,
                                                1,
                                                3,
                                                0,
                                                3,
                                                0,
                                                1,
                                                0,
                                                3,
                                                "F",
                                                0,
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                3,
                                                3,
                                                3,
                                                3,
                                                0,
                                                0
                                            ],
                              "gols":  24
                          },
                          {
                              "nome":  "Manoel",
                              "pontos":  29,
                              "jogos":  18,
                              "historico":  [
                                                "F",
                                                0,
                                                1,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                1,
                                                0,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                3,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                "F",
                                                3,
                                                "F",
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                0,
                                                "F",
                                                0
                                            ],
                              "gols":  5
                          },
                          {
                              "nome":  "Luciano",
                              "pontos":  28,
                              "jogos":  26,
                              "historico":  [
                                                3,
                                                0,
                                                1,
                                                0,
                                                "F",
                                                3,
                                                3,
                                                "F",
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3,
                                                3,
                                                0,
                                                0,
                                                3,
                                                0,
                                                3,
                                                3,
                                                3,
                                                0,
                                                0,
                                                0
                                            ],
                              "gols":  23
                          },
                          {
                              "nome":  "Pedro",
                              "pontos":  28,
                              "jogos":  15,
                              "historico":  [
                                                "F",
                                                3,
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                1,
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                0,
                                                3,
                                                "F",
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                "F"
                                            ],
                              "gols":  19
                          },
                          {
                              "nome":  "Andrey",
                              "pontos":  26,
                              "jogos":  20,
                              "historico":  [
                                                3,
                                                3,
                                                1,
                                                3,
                                                "F",
                                                "F",
                                                "F",
                                                1,
                                                3,
                                                3,
                                                "F",
                                                0,
                                                "F",
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                "F",
                                                0,
                                                3,
                                                "F",
                                                0
                                            ],
                              "gols":  16
                          },
                          {
                              "nome":  "Lucas Carneiro",
                              "pontos":  28,
                              "jogos":  25,
                              "historico":  [
                                                3,
                                                0,
                                                1,
                                                3,
                                                0,
                                                0,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                0,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3
                                            ],
                              "gols":  32
                          },
                          {
                              "nome":  "Carlos",
                              "pontos":  25,
                              "jogos":  21,
                              "historico":  [
                                                0,
                                                "F",
                                                1,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                3,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                0,
                                                3,
                                                0,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                0,
                                                "F",
                                                0,
                                                "F"
                                            ],
                              "gols":  28
                          },
                          {
                              "nome":  "Luan",
                              "pontos":  25,
                              "jogos":  24,
                              "historico":  [
                                                0,
                                                0,
                                                1,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                3,
                                                0,
                                                0,
                                                0
                                            ],
                              "gols":  28
                          },
                          {
                              "nome":  "Ivair",
                              "pontos":  24,
                              "jogos":  18,
                              "historico":  [
                                                0,
                                                0,
                                                "F",
                                                0,
                                                3,
                                                "F",
                                                0,
                                                "F",
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                "F",
                                                "F",
                                                "F",
                                                3
                                            ],
                              "gols":  8
                          },
                          {
                              "nome":  "Wendril",
                              "pontos":  12,
                              "jogos":  4,
                              "historico":  [
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                3,
                                                3,
                                                3,
                                                3
                                            ],
                              "gols":  3
                          },
                          {
                              "nome":  "Maicon",
                              "pontos":  1,
                              "jogos":  2,
                              "historico":  [
                                                "F",
                                                "F",
                                                1,
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                0,
                                                "F",
                                                "F"
                                            ],
                              "gols":  0
                          }
                      ],
    "goleiros":  [
                     {
                         "nome":  "Ivan",
                         "pontos":  34,
                         "jogos":  22,
                         "historico":  [
                                           3,
                                           3,
                                           1,
                                           0,
                                           "F",
                                           3,
                                           "F",
                                           "F",
                                           0,
                                           3,
                                           3,
                                           3,
                                           0,
                                           0,
                                           3,
                                           3,
                                           0,
                                           0,
                                           "F",
                                           3,
                                           0,
                                           3,
                                           0,
                                           0,
                                           "F",
                                           0,
                                           3,
                                           "F"
                                       ],
                         "gols":  0
                     },
                     {
                         "nome":  "Flávio",
                         "pontos":  30,
                         "jogos":  21,
                         "historico":  [
                                           "F",
                                           0,
                                           "F",
                                           0,
                                           3,
                                           0,
                                           "F",
                                           "F",
                                           3,
                                           0,
                                           0,
                                           0,
                                           3,
                                           3,
                                           0,
                                           0,
                                           3,
                                           "F",
                                           3,
                                           "F",
                                           3,
                                           "F",
                                           3,
                                           3,
                                           3,
                                           0,
                                           0,
                                           0
                                       ],
                         "gols":  0
                     }
                 ],
    "meta":  {
                 "aba":  "2026",
                 "rodadaAtual":  28,
                 "destaque":  {
                                  "nome":  "Bruno",
                                  "gols":  1,
                                  "jogos":  27,
                                  "rodada":  28
                              }
             }
};
