var DADOS = {
    "classificacao":  [
                          {
                              "nome":  "João",
                              "pontos":  50,
                              "jogos":  22,
                              "historico":  [
                                                3,
                                                3,
                                                1,
                                                3,
                                                3,
                                                3,
                                                0,
                                                1,
                                                3,
                                                3,
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                3,
                                                3,
                                                0,
                                                3,
                                                3
                                            ],
                              "gols":  43
                          },
                          {
                              "nome":  "Tampico",
                              "pontos":  34,
                              "jogos":  21,
                              "historico":  [
                                                "F",
                                                3,
                                                1,
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3,
                                                3,
                                                3,
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                3,
                                                0
                                            ],
                              "gols":  33
                          },
                          {
                              "nome":  "Jorge",
                              "pontos":  34,
                              "jogos":  22,
                              "historico":  [
                                                "F",
                                                3,
                                                1,
                                                0,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                3,
                                                3,
                                                3,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                0,
                                                3,
                                                3,
                                                0,
                                                3
                                            ],
                              "gols":  39
                          },
                          {
                              "nome":  "Bruno",
                              "pontos":  32,
                              "jogos":  25,
                              "historico":  [
                                                3,
                                                0,
                                                1,
                                                3,
                                                0,
                                                3,
                                                0,
                                                1,
                                                0,
                                                3,
                                                "F",
                                                0,
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                3,
                                                3,
                                                3,
                                                3
                                            ],
                              "gols":  23
                          },
                          {
                              "nome":  "Manoel",
                              "pontos":  29,
                              "jogos":  17,
                              "historico":  [
                                                "F",
                                                0,
                                                1,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                1,
                                                0,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                3,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                "F",
                                                3,
                                                "F",
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                0
                                            ],
                              "gols":  5
                          },
                          {
                              "nome":  "Luciano",
                              "pontos":  28,
                              "jogos":  24,
                              "historico":  [
                                                3,
                                                0,
                                                1,
                                                0,
                                                "F",
                                                3,
                                                3,
                                                "F",
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3,
                                                3,
                                                0,
                                                0,
                                                3,
                                                0,
                                                3,
                                                3,
                                                3,
                                                0
                                            ],
                              "gols":  23
                          },
                          {
                              "nome":  "Andrey",
                              "pontos":  26,
                              "jogos":  19,
                              "historico":  [
                                                3,
                                                3,
                                                1,
                                                3,
                                                "F",
                                                "F",
                                                "F",
                                                1,
                                                3,
                                                3,
                                                "F",
                                                0,
                                                "F",
                                                0,
                                                0,
                                                3,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                "F",
                                                0,
                                                3
                                            ],
                              "gols":  16
                          },
                          {
                              "nome":  "Lucas Carneiro",
                              "pontos":  25,
                              "jogos":  23,
                              "historico":  [
                                                3,
                                                0,
                                                1,
                                                3,
                                                0,
                                                0,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                0,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                0,
                                                0,
                                                0
                                            ],
                              "gols":  30
                          },
                          {
                              "nome":  "Carlos",
                              "pontos":  25,
                              "jogos":  20,
                              "historico":  [
                                                0,
                                                "F",
                                                1,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                3,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                0,
                                                3,
                                                0,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                0,
                                                0,
                                                "F"
                                            ],
                              "gols":  27
                          },
                          {
                              "nome":  "Luan",
                              "pontos":  25,
                              "jogos":  22,
                              "historico":  [
                                                0,
                                                0,
                                                1,
                                                0,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                0,
                                                3,
                                                "F",
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                3,
                                                0
                                            ],
                              "gols":  27
                          },
                          {
                              "nome":  "Pedro",
                              "pontos":  25,
                              "jogos":  14,
                              "historico":  [
                                                "F",
                                                3,
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                1,
                                                3,
                                                3,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                0,
                                                3,
                                                "F",
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                0,
                                                3,
                                                "F"
                                            ],
                              "gols":  17
                          },
                          {
                              "nome":  "Ivair",
                              "pontos":  21,
                              "jogos":  17,
                              "historico":  [
                                                0,
                                                0,
                                                "F",
                                                0,
                                                3,
                                                "F",
                                                0,
                                                "F",
                                                3,
                                                0,
                                                "F",
                                                "F",
                                                3,
                                                "F",
                                                3,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                3,
                                                0,
                                                "F",
                                                0,
                                                "F",
                                                "F"
                                            ],
                              "gols":  7
                          },
                          {
                              "nome":  "Wendril",
                              "pontos":  6,
                              "jogos":  2,
                              "historico":  [
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                3,
                                                3
                                            ],
                              "gols":  2
                          },
                          {
                              "nome":  "Maicon",
                              "pontos":  1,
                              "jogos":  2,
                              "historico":  [
                                                "F",
                                                "F",
                                                1,
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                "F",
                                                0
                                            ],
                              "gols":  0
                          },
                          {
                              "nome":  "Edgar",
                              "pontos":  0,
                              "jogos":  12,
                              "historico":  [
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                0,
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                "F",
                                                "F",
                                                0,
                                                "F",
                                                "F",
                                                0,
                                                "F",
                                                0,
                                                "F",
                                                0,
                                                "F",
                                                "F",
                                                0,
                                                0,
                                                0,
                                                "F",
                                                "F"
                                            ],
                              "gols":  22
                          }
                      ],
    "goleiros":  [
                     {
                         "nome":  "Ivan",
                         "pontos":  31,
                         "jogos":  21,
                         "historico":  [
                                           3,
                                           3,
                                           1,
                                           0,
                                           "F",
                                           3,
                                           "F",
                                           "F",
                                           0,
                                           3,
                                           3,
                                           3,
                                           0,
                                           0,
                                           3,
                                           3,
                                           0,
                                           0,
                                           "F",
                                           3,
                                           0,
                                           3,
                                           0,
                                           0,
                                           "F",
                                           0
                                       ],
                         "gols":  0
                     },
                     {
                         "nome":  "Flávio",
                         "pontos":  30,
                         "jogos":  18,
                         "historico":  [
                                           "F",
                                           0,
                                           "F",
                                           "F",
                                           3,
                                           0,
                                           "F",
                                           "F",
                                           3,
                                           0,
                                           0,
                                           0,
                                           3,
                                           3,
                                           0,
                                           0,
                                           3,
                                           "F",
                                           3,
                                           "F",
                                           3,
                                           "F",
                                           3,
                                           3,
                                           3,
                                           0
                                       ],
                         "gols":  0
                     }
                 ],
    "meta":  {
                 "aba":  "2026",
                 "rodadaAtual":  26,
                 "destaque":  {
                                  "nome":  "Bruno",
                                  "gols":  2,
                                  "jogos":  25,
                                  "rodada":  26
                              }
             }
};
